import PDFDocument from 'pdfkit';
import { ProjectBlueprint } from '../../models/project.types.js';

export async function generatePDF(project: ProjectBlueprint): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers: Buffer[] = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Colors
      const primaryColor = '#7A263A'; // Burgundy
      const charcoal = '#202020';
      const mutedText = '#666666';

      // Document Header
      doc.fontSize(22).fillColor(primaryColor).font('Helvetica-Bold').text(project.title, { align: 'left' });
      doc.moveDown(0.25);
      doc.fontSize(11).fillColor(mutedText).font('Helvetica').text(`Domain: ${project.domain}  |  Complexity: ${project.complexity}  |  Mode: ${project.agent_mode.toUpperCase()}`);
      doc.moveDown(0.5);
      doc.strokeColor('#E5E0D7').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(1);

      // Section: Tagline
      if (project.tagline) {
        doc.fontSize(12).fillColor(charcoal).font('Helvetica-Oblique').text(`"${project.tagline}"`);
        doc.moveDown(0.75);
      }

      // Section 1: Problem Statement
      doc.fontSize(14).fillColor(primaryColor).font('Helvetica-Bold').text('1. Problem Statement');
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor(charcoal).font('Helvetica').text(project.problem_statement, { lineGap: 3 });
      doc.moveDown(1);

      // Section 2: Objectives
      doc.fontSize(14).fillColor(primaryColor).font('Helvetica-Bold').text('2. Project Objectives');
      doc.moveDown(0.3);
      project.objectives.forEach((obj, idx) => {
        doc.fontSize(10).fillColor(charcoal).font('Helvetica').text(`•  ${obj}`, { indent: 10, lineGap: 2 });
      });
      doc.moveDown(1);

      // Section 3: Architecture Summary
      doc.fontSize(14).fillColor(primaryColor).font('Helvetica-Bold').text('3. System Architecture & Component Flow');
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor(charcoal).font('Helvetica').text(project.architecture.summary, { lineGap: 3 });
      doc.moveDown(0.5);
      doc.fontSize(9).fillColor(primaryColor).font('Courier-Bold').text(`Data Flow: ${project.architecture.diagramDescription}`, { indent: 10 });
      doc.moveDown(1);

      // Section 4: Tech Stack
      doc.fontSize(14).fillColor(primaryColor).font('Helvetica-Bold').text('4. Recommended Technology Stack');
      doc.moveDown(0.3);
      project.tech_stack.forEach((tech) => {
        doc.fontSize(10).fillColor(charcoal).font('Helvetica-Bold').text(`${tech.category}: `, { continued: true });
        doc.font('Helvetica').text(`${tech.item} — ${tech.rationale}`, { lineGap: 2 });
      });
      doc.moveDown(1);

      // Section 5: Roadmap
      doc.fontSize(14).fillColor(primaryColor).font('Helvetica-Bold').text('5. Phased Development Roadmap');
      doc.moveDown(0.3);
      project.roadmap.forEach((phase) => {
        doc.fontSize(10).fillColor(primaryColor).font('Helvetica-Bold').text(`${phase.phase} (${phase.duration})`);
        phase.tasks.forEach((t) => {
          doc.fontSize(9).fillColor(charcoal).font('Helvetica').text(`  - ${t}`, { indent: 10 });
        });
        doc.moveDown(0.4);
      });
      doc.moveDown(0.5);

      // Section 6: Viva Defense Q&A
      doc.fontSize(14).fillColor(primaryColor).font('Helvetica-Bold').text('6. Viva Examination Defense Q&A');
      doc.moveDown(0.3);
      project.viva_questions.forEach((viva, idx) => {
        doc.fontSize(10).fillColor(charcoal).font('Helvetica-Bold').text(`Q${idx + 1}: ${viva.question}`);
        doc.fontSize(9).fillColor(mutedText).font('Helvetica').text(`Answer: ${viva.answer}`, { lineGap: 2 });
        doc.moveDown(0.5);
      });

      // Footer
      doc.fontSize(8).fillColor(mutedText).text(`\nGenerated by ProjectMind AI • ${new Date().toLocaleDateString()}`, { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
