import pptxgen from 'pptxgenjs';
import { ProjectBlueprint } from '../../models/project.types.js';

export async function generatePPT(project: ProjectBlueprint): Promise<Buffer> {
  const PptxClass = (pptxgen as any).default || pptxgen;
  const pptx = new PptxClass();

  pptx.layout = 'LAYOUT_16x9';

  // Slide 1: Title Slide
  const slide1 = pptx.addSlide();
  slide1.background = { color: 'FAF8F5' };
  slide1.addText(project.title, {
    x: 0.8,
    y: 1.8,
    w: 8.5,
    h: 1.5,
    fontSize: 28,
    bold: true,
    color: '7A263A',
  });
  slide1.addText(project.tagline || `Domain: ${project.domain}`, {
    x: 0.8,
    y: 3.5,
    w: 8.5,
    h: 0.8,
    fontSize: 16,
    italic: true,
    color: '555555',
  });
  slide1.addText(`Complexity: ${project.complexity}  |  Generated by ProjectMind AI`, {
    x: 0.8,
    y: 4.5,
    w: 8.5,
    h: 0.5,
    fontSize: 12,
    color: '888888',
  });

  // Slide 2: Problem Statement & Objectives
  const slide2 = pptx.addSlide();
  slide2.background = { color: 'FAF8F5' };
  slide2.addText('Problem Statement & Objectives', {
    x: 0.8,
    y: 0.6,
    w: 8.5,
    h: 0.6,
    fontSize: 20,
    bold: true,
    color: '7A263A',
  });
  slide2.addText(`Problem Statement:\n${project.problem_statement}`, {
    x: 0.8,
    y: 1.4,
    w: 8.5,
    h: 1.6,
    fontSize: 12,
    color: '202020',
  });
  const objectivesText = project.objectives.map((o) => `• ${o}`).join('\n');
  slide2.addText(`Key Objectives:\n${objectivesText}`, {
    x: 0.8,
    y: 3.2,
    w: 8.5,
    h: 2.0,
    fontSize: 12,
    color: '202020',
  });

  // Slide 3: Architecture & Data Flow
  const slide3 = pptx.addSlide();
  slide3.background = { color: 'FAF8F5' };
  slide3.addText('System Architecture & Data Flow', {
    x: 0.8,
    y: 0.6,
    w: 8.5,
    h: 0.6,
    fontSize: 20,
    bold: true,
    color: '7A263A',
  });
  slide3.addText(`Overview:\n${project.architecture.summary}`, {
    x: 0.8,
    y: 1.4,
    w: 8.5,
    h: 1.5,
    fontSize: 12,
    color: '202020',
  });
  slide3.addText(`Pipeline Flow:\n${project.architecture.diagramDescription}`, {
    x: 0.8,
    y: 3.2,
    w: 8.5,
    h: 1.8,
    fontSize: 13,
    bold: true,
    color: '7A263A',
    fill: { color: 'FFFFFF' },
  });

  // Slide 4: Technology Stack
  const slide4 = pptx.addSlide();
  slide4.background = { color: 'FAF8F5' };
  slide4.addText('Technology Stack & Rationale', {
    x: 0.8,
    y: 0.6,
    w: 8.5,
    h: 0.6,
    fontSize: 20,
    bold: true,
    color: '7A263A',
  });
  const techLines = project.tech_stack.map((t) => `${t.category}: ${t.item} (${t.rationale})`).join('\n\n');
  slide4.addText(techLines, {
    x: 0.8,
    y: 1.4,
    w: 8.5,
    h: 3.8,
    fontSize: 12,
    color: '202020',
  });

  // Slide 5: Roadmap & Viva Defense
  const slide5 = pptx.addSlide();
  slide5.background = { color: 'FAF8F5' };
  slide5.addText('Development Roadmap & Defense Questions', {
    x: 0.8,
    y: 0.6,
    w: 8.5,
    h: 0.6,
    fontSize: 20,
    bold: true,
    color: '7A263A',
  });
  const roadmapText = project.roadmap.map((r) => `${r.phase} (${r.duration})`).join('  ➔  ');
  slide5.addText(`Roadmap Flow: ${roadmapText}`, {
    x: 0.8,
    y: 1.4,
    w: 8.5,
    h: 0.8,
    fontSize: 12,
    bold: true,
    color: '7A263A',
  });
  const topViva = project.viva_questions.slice(0, 2).map((v) => `Q: ${v.question}\nA: ${v.answer}`).join('\n\n');
  slide5.addText(`Key Defense Points:\n${topViva}`, {
    x: 0.8,
    y: 2.4,
    w: 8.5,
    h: 2.8,
    fontSize: 11,
    color: '202020',
  });

  const buffer = (await pptx.write({ outputType: 'nodebuffer' })) as Buffer;
  return buffer;
}
