import { ProjectBlueprint } from '@/types/project';
import { MOCK_PROJECTS } from '../mock/mockData';

const USE_MOCK = process.env.NEXT_PUBLIC_USE_MOCK_DATA === 'true';
const EXPRESS_BASE_URL = process.env.NEXT_PUBLIC_EXPRESS_API_URL || 'http://localhost:5000/api/v1';

export class ProjectService {
  /**
   * Fetch all user projects from Express backend.
   */
  static async getAllProjects(token?: string | null): Promise<ProjectBlueprint[]> {
    if (USE_MOCK) {
      return Promise.resolve(MOCK_PROJECTS);
    }

    try {
      const headers: Record<string, string> = {};
      if (token) headers['Authorization'] = `Bearer ${token}`;

      const res = await fetch(`${EXPRESS_BASE_URL}/projects`, { headers });
      if (!res.ok) throw new Error('Failed to fetch projects');
      const data = await res.json();
      return data.data || data;
    } catch (err) {
      console.warn('Backend query failed, using demo project list.', err);
      return MOCK_PROJECTS;
    }
  }

  /**
   * Fetch single project blueprint by ID with ownership verification.
   */
  static async getProjectById(id: string, token?: string | null): Promise<ProjectBlueprint | null> {
    if (USE_MOCK) {
      const project = MOCK_PROJECTS.find((p) => p.id === id) || MOCK_PROJECTS[0];
      return Promise.resolve(project);
    }

    try {
      const headers: Record<string, string> = {};
      if (token) headers['Authorization'] = `Bearer ${token}`;

      const res = await fetch(`${EXPRESS_BASE_URL}/projects/${id}`, { headers });
      if (!res.ok) throw new Error('Project not found');
      const data = await res.json();
      return data.data || data;
    } catch (err) {
      return MOCK_PROJECTS[0];
    }
  }

  /**
   * Request export file download from backend export service.
   */
  static async exportProject(id: string, format: 'pdf' | 'docx' | 'ppt' | 'md', token?: string | null): Promise<Blob> {
    if (USE_MOCK) {
      const dummyContent = `# Project Blueprint Export (${format.toUpperCase()})\nProject ID: ${id}\nGenerated by ProjectMind AI`;
      return new Blob([dummyContent], { type: 'text/plain' });
    }

    const headers: Record<string, string> = {};
    if (token) headers['Authorization'] = `Bearer ${token}`;

    const res = await fetch(`${EXPRESS_BASE_URL}/export/${id}/${format}`, { headers });
    if (!res.ok) throw new Error('Export download failed');
    return await res.blob();
  }
}
